apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pdfmagic
  labels:
    app: pdfmagic
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pdfmagic
    spec:
      containers:
      - name: pdfmagic
        image: 0track/pdfmagic
        resources:
          requests:
            cpu: 0.5
        ports:
          - containerPort: 8080
